#!/usr/bin/env bash
set -e

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
REPO_RAW="https://raw.githubusercontent.com/tomlen045/ops-skills/main"
REPO_JSD="https://cdn.jsdelivr.net/gh/tomlen045/ops-skills@main"
SKILLS=(sre-incident-commander k8s-security-reviewer linux-security-hardener prometheus-architect infra-diagram-gen postmortem-writer terraform-guardian log-detective docker-reviewer oncall-runbook)

echo -e "${CYAN}"
echo "  ██████╗ ███████╗███████╗    ███████╗██╗  ██╗██╗██╗     ██╗     ███████╗"
echo "  ██╔═══██╗██╔════╝██╔════╝    ██╔════╝██║  ██║██║██║     ██║     ██╔════╝"
echo "  ██║   ██║███████╗███████╗    ███████╗███████║██║██║     ██║     █████╗  "
echo "  ██║   ██║╚════██║╚════██║    ╚════██║██╔══██║██║██║     ██║     ██╔══╝  "
echo "  ╚██████╔╝███████║███████║    ███████║██║  ██║██║███████╗███████╗███████╗"
echo "   ╚═════╝ ╚══════╝╚══════╝    ╚══════╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚══════╝"
echo -e "${NC}"
echo "  AI Skills for DevOps / SRE — Make your AI assistant ops-smart"
echo ""

# fetch <repo-path> -> stdout to /tmp/ops-skill.tmp ; tries raw first, jsdelivr mirror fallback
fetch() {
  curl -sL --max-time 15 "$REPO_RAW/$1" -o /tmp/ops-skill.tmp 2>/dev/null
  if [[ ! -s /tmp/ops-skill.tmp ]] || grep -q "404: Not Found" /tmp/ops-skill.tmp 2>/dev/null; then
    curl -sL --max-time 15 "$REPO_JSD/$1" -o /tmp/ops-skill.tmp 2>/dev/null
  fi
  [[ -s /tmp/ops-skill.tmp ]] && ! grep -qE "404: Not Found|Couldn't find the requested file|Package size exceeded" /tmp/ops-skill.tmp 2>/dev/null
}

install_native() {
  local base="${HOME}/.claude/skills"
  mkdir -p "$base"
  for skill in "${SKILLS[@]}"; do
    echo -n "  Installing $skill... "
    if fetch "native/$skill/SKILL.md"; then
      mkdir -p "$base/$skill"
      cp /tmp/ops-skill.tmp "$base/$skill/SKILL.md"
      echo -e "${GREEN}✓${NC}"
    else
      echo -e "${YELLOW}skip${NC}"
    fi
  done
  rm -f /tmp/ops-skill.tmp
  echo -e "\n  ${GREEN}✅ 10 skills installed to ~/.claude/skills/${NC}"
  echo "  Restart your Claude Code / agent session and they auto-activate."
  echo "  Works with any harness that reads SKILL.md (Claude Code, Codex, Cursor, etc.)"
}

install_claude_md() {
  local dest="CLAUDE.md"
  echo "# Ops Skills — AI assistant configuration for DevOps/SRE work" > "$dest"
  echo "# Generated by ops-skills (github.com/tomlen045/ops-skills)" >> "$dest"
  echo "" >> "$dest"
  for skill in "${SKILLS[@]}"; do
    echo -n "  Downloading $skill... "
    if fetch "skills/$skill.md"; then
      echo -e "\n---\n\n## Skill: $skill\n" >> "$dest"
      cat /tmp/ops-skill.tmp >> "$dest"
      echo -e "${GREEN}✓${NC}"
    else
      echo -e "${YELLOW}skip${NC}"
    fi
  done
  rm -f /tmp/ops-skill.tmp
  echo -e "\n  ${GREEN}✅ Installed to $dest${NC}"
}

install_cursor() {
  local dest=".cursorrules"
  echo "" > "$dest"
  for skill in "${SKILLS[@]}"; do
    echo -n "  Downloading $skill... "
    if fetch "skills/$skill.md"; then
      echo -e "\n# ═══════════════════════════════════════════" >> "$dest"
      echo -e "# SKILL: $skill\n# ═══════════════════════════════════════════\n" >> "$dest"
      cat /tmp/ops-skill.tmp >> "$dest"
      echo -e "${GREEN}✓${NC}"
    else
      echo -e "${YELLOW}skip${NC}"
    fi
  done
  rm -f /tmp/ops-skill.tmp
  echo -e "\n  ${GREEN}✅ Installed to $dest${NC}"
}

if [[ -n "$1" ]]; then
  choice="$1"
else
  echo "  Which install mode?"
  echo "  1) Native skills → ~/.claude/skills/ (recommended, auto-activates)"
  echo "  2) Single-file CLAUDE.md"
  echo "  3) Cursor .cursorrules"
  echo "  4) Both CLAUDE.md + .cursorrules"
  echo "  5) Just download the skill files"
  read -p "  Choice [1-5]: " choice
fi

case $choice in
  1) install_native ;;
  2) install_claude_md ;;
  3) install_cursor ;;
  4) install_claude_md; echo ""; install_cursor ;;
  5)
    mkdir -p ops-skills
    for skill in "${SKILLS[@]}"; do
      fetch "skills/$skill.md" && cp /tmp/ops-skill.tmp "ops-skills/$skill.md"
      echo "  Downloaded: ops-skills/$skill.md"
    done
    rm -f /tmp/ops-skill.tmp
    echo -e "\n  ${GREEN}✅ Skills downloaded to ./ops-skills/${NC}"
    ;;
  *) echo "Invalid choice"; exit 1 ;;
esac

echo ""
echo -e "${CYAN}  ─────────────────────────────────────────${NC}"
echo -e "  ${GREEN}Done! Your AI assistant is now ops-smart.${NC}"
echo ""
echo "  What you get:"
echo "  • Incident response with SEV triage        • K8s manifest security review (15+ checks)"
echo "  • Linux hardening (CIS)                    • Prometheus alert rules that don't suck"
echo "  • Auto-generated architecture diagrams     • Postmortem + runbook templates"
echo "  • Terraform security review                • Log analysis & error clustering"
echo "  • Docker best-practices review             • On-call runbook generator"
echo ""
echo "  ⭐ Found this useful? Star the repo:"
echo "  https://github.com/tomlen045/ops-skills"
echo -e "${NC}"
