#!/usr/bin/env bash
set -e

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
REPO="https://raw.githubusercontent.com/tomlen045/ops-skills/main"
SKILLS=(sre-incident-commander k8s-security-reviewer linux-security-hardener prometheus-architect infra-diagram-gen postmortem-writer terraform-guardian log-detective docker-reviewer oncall-runbook)

echo -e "${CYAN}"
echo "  ██████╗ ███████╗███████╗    ███████╗██╗  ██╗██╗██╗     ██╗     ███████╗"
echo "  ██╔═══██╗██╔════╝██╔════╝    ██╔════╝██║  ██║██║██║     ██║     ██╔════╝"
echo "  ██║   ██║███████╗███████╗    ███████╗███████║██║██║     ██║     █████╗  "
echo "  ██║   ██║╚════██║╚════██║    ╚════██║██╔══██║██║██║     ██║     ██╔══╝  "
echo "  ╚██████╔╝███████║███████║    ███████║██║  ██║██║███████╗███████╗███████╗"
echo "   ╚═════╝ ╚══════╝╚══════╝    ╚══════╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚══════╝"
echo -e "${NC}"
echo "  AI Skills for DevOps / SRE — Make your AI assistant ops-smart"
echo ""

# Detect which tool the user has
echo "  Which AI coding assistant do you use?"
echo "  1) Claude Code (CLAUDE.md)"
echo "  2) Cursor (.cursorrules)"
echo "  3) Both"
echo "  4) Just download the skill files"
read -p "  Choice [1-4]: " choice

install_cursor() {
  local dest="${1:-.cursorrules}"
  echo "" > "$dest"
  for skill in "${SKILLS[@]}"; do
    echo -n "  Downloading $skill... "
    curl -sL "$REPO/skills/$skill.md" -o /tmp/ops-skill.tmp 2>/dev/null
    if [[ -s /tmp/ops-skill.tmp ]]; then
      echo -e "\n# ═══════════════════════════════════════════" >> "$dest"
      echo -e "# SKILL: $skill\n# ═══════════════════════════════════════════\n" >> "$dest"
      cat /tmp/ops-skill.tmp >> "$dest"
      echo -e "${GREEN}✓${NC}"
    else
      echo -e "${YELLOW}skip${NC}"
    fi
  done
  rm -f /tmp/ops-skill.tmp
  echo -e "\n  ${GREEN}✅ Installed to $dest${NC}"
  echo "  Place this file in your project root and Cursor will pick it up."
}

install_claude() {
  local dest="${1:-CLAUDE.md}"
  echo "" > "$dest"
  echo "# Ops Skills — AI assistant configuration for DevOps/SRE work" >> "$dest"
  echo "# Generated by ops-skills (github.com/tomlen045/ops-skills)" >> "$dest"
  echo "" >> "$dest"
  for skill in "${SKILLS[@]}"; do
    echo -n "  Downloading $skill... "
    curl -sL "$REPO/skills/$skill.md" -o /tmp/ops-skill.tmp 2>/dev/null
    if [[ -s /tmp/ops-skill.tmp ]]; then
      echo -e "\n---\n\n## Skill: $skill\n" >> "$dest"
      cat /tmp/ops-skill.tmp >> "$dest"
      echo -e "${GREEN}✓${NC}"
    else
      echo -e "${YELLOW}skip${NC}"
    fi
  done
  rm -f /tmp/ops-skill.tmp
  echo -e "\n  ${GREEN}✅ Installed to $dest${NC}"
  echo "  Place this file in your project root and Claude Code will pick it up."
}

case $choice in
  1) install_claude ;;
  2) install_cursor ;;
  3) install_claude; echo ""; install_cursor ;;
  4)
    mkdir -p ops-skills
    for skill in "${SKILLS[@]}"; do
      curl -sL "$REPO/skills/$skill.md" -o "ops-skills/$skill.md"
      echo "  Downloaded: ops-skills/$skill.md"
    done
    echo -e "\n  ${GREEN}✅ Skills downloaded to ./ops-skills/${NC}"
    ;;
  *) echo "Invalid choice"; exit 1 ;;
esac

echo ""
echo -e "${CYAN}  ─────────────────────────────────────────${NC}"
echo -e "  ${GREEN}Done! Your AI assistant is now ops-smart.${NC}"
echo ""
echo "  What you get:"
echo "  • Incident response with proper severity triage"
echo "  • K8s manifest security review (15+ checks)"
echo "  • Linux hardening with CIS benchmarks"
echo "  • Prometheus alert rules that don't suck"
echo "  • Auto-generated architecture diagrams"
echo "  • Postmortem + runbook templates"
echo "  • Terraform security review"
echo "  • Log analysis with pattern recognition"
echo "  • Docker best practices review"
echo "  • On-call runbook generator"
echo ""
echo "  ⭐ Found this useful? Star the repo:"
echo "  https://github.com/tomlen045/ops-skills"
echo -e "${NC}"
